version: 2
updates:
  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      testing:
        patterns:
          - "coverlet*"
          - "Microsoft.NET.Test*"
          - "NUnit*"
          - "Shouldly"
      appium:
        patterns:
          - "Appium*"
      analyzers:
        patterns:
          - "Microsoft.SourceLink*"
      flaui:
        patterns:
          - "FlaUI*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    commit-message:
      prefix: "ci"
      include: "scope"
