<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Legerity.Core\Legerity.Core.csproj" />
    <ProjectReference Include="..\..\src\Legerity.Windows\Legerity.Windows.csproj" />
    <ProjectReference Include="..\..\src\Legerity.WinUI\Legerity.WinUI.csproj" />
  </ItemGroup>

</Project>