<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Product>Legerity - Framework for UI testing with Selenium/Appium</Product>
    <Description>Meta-package for the Legerity UI testing framework. Includes core, Windows, Android, iOS, and Web element wrapper packages.</Description>
    <PackageTags>UI Test Appium Selenium WinAppDriver LegerityWindowsDriver POP Windows UWP WinUI Web Android IOS Xamarin MAUI Uno</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Legerity.Android\Legerity.Android.csproj" />
    <ProjectReference Include="..\Legerity.Core\Legerity.Core.csproj" />
    <ProjectReference Include="..\Legerity.IOS\Legerity.IOS.csproj" />
    <ProjectReference Include="..\Legerity.Web\Legerity.Web.csproj" />
    <ProjectReference Include="..\Legerity.Windows\Legerity.Windows.csproj" />
  </ItemGroup>

</Project>
