<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Product>Legerity for iOS - Framework for UI testing with Selenium/Appium</Product>
    <Description>
      This package is an iOS core extension to the Legerity framework for speeding up the development of automated UI tests with Selenium/Appium including:
      - IOSElementWrapper, for creating element wrappers for custom controls
    </Description>
    <PackageTags>UI Test Appium Selenium IOSDriver IOS Xamarin MAUI Uno</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Legerity.Core\Legerity.Core.csproj" />
  </ItemGroup>

</Project>
