<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Selenium.WebDriver.ChromeDriver" Version="148.0.7778.16700" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Legerity.Core\Legerity.Core.csproj" />
    <ProjectReference Include="..\..\src\Legerity.Web\Legerity.Web.csproj" />
  </ItemGroup>

</Project>