<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageType>Template</PackageType>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Product>Legerity Templates - Project templates for the Legerity UI testing framework</Product>
    <Description>dotnet new project templates for creating Legerity UI test projects with NUnit. Includes templates for Android, iOS, Web, Windows, and cross-platform applications.</Description>
    <PackageTags>UI Test Appium Selenium WinAppDriver LegerityWindowsDriver POP Windows WinUI Web Android IOS Xamarin MAUI Uno</PackageTags>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
    <Version>1.0.0.0</Version>
    <Authors>MADE Apps</Authors>
    <Company>MADE Apps</Company>
    <Copyright>Copyright (C) MADE Apps. All rights reserved.</Copyright>
    <PackageProjectUrl>https://github.com/MADE-Apps/legerity</PackageProjectUrl>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageIcon>ProjectIcon.png</PackageIcon>
    <PackageReleaseNotes>https://github.com/MADE-Apps/legerity/releases</PackageReleaseNotes>
    <IncludeContentInPack>true</IncludeContentInPack>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <ContentTargetFolders>content</ContentTargetFolders>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\assets\ProjectIcon.png" Pack="true" PackagePath=""/>
    <None Include="..\..\LICENSE" Pack="true" PackagePath=""/>
    <Content Include="templates\**\*" Exclude="templates\**\bin\**;templates\**\obj\**" />
    <Compile Remove="**\*" />
  </ItemGroup>

</Project>